- menu_screen.py
~sui has mentioned that botany always crashes for him with the stack trace:  
Traceback (most recent call last):   File "/home/curiouser/botany/botany.py", line 543, in <module>     botany_menu == CursedMenu(my_plant,my_data)   File "/home/curiouser/botany/menu_screen.py", line 19, in __init__     curses.curs_set(0) _curses.error: curs_set() returned ERR
According to the docs, an error will be returned when the terminal does not support the visibility requested.
Appearently hiding the cursor is not supported in ~sui's terminal (cmder).
To keep botany as accesible as possible I suggest to ignore this error.
> Ignore curs_set(0) error

- menu_screen.py
Only use colours when the terminal supports them.
The same highlighting can be used with `curses.A_REVERSE`. I think `curses.A_STANDOUT` could work as well
> don't try to use colours if unsupported; fix #7

- botany.py
First write all the dump to a temporary file.
Rename temp file to actual file name when done.
This prevents savefile corruption when botany crashes while writing to the save file.
> dump safely by writing to tempfile

- botany.py
- menu_screen.py
put cleanup in finally block so it happens no matter the crash
this should prevend scrambled lines all over the terminal
> properly clean up after crash

- menu_screen.py
This PR adds some control to the garden screen:
- ESC, q, x: quit
- SPC, RET, PGDOWN: next page. If used at the last page, quits.
- BACKSPACE, PGUP: previous page
- j, DOWN: next line
- k, UP: previous line
- s: sort list, then alternate between ascending and descending order. The column used to sort is determined by the next key:
- n, 1: name
- a, 2: age
- s, 3: score
- d, 4: description
- f, /: filter/search items. This prompts for a regex and keeps lines containing the regex. If the regex is invalid, nothing is matched.
It also:
- fixes a few display bugs (prevents long lines from overflowing and integer score in the garden)
- generalizes the `get_user_string` function (can now be used for a dynamic character set instead of just alphanumeric) and fixes its redraw (used a static offset …
> Add controls for the garden screen

- menu_screen.py
The display sometimes crashed (characters drawn at random places, text not cleared, etc.) at startup or during a session, sometimes even stopping the entire program. This PR *should* solve the problem. It adds a lock around code that draws on screen, preventing both threads to draw at the same time.
> Fix race conditions messing up the display

- completer.py
- menu_screen.py
This PR adds loop-based autocompletion for logins when visiting.
When pressing tab, the input is changed to the next login in the list. This repeats until the end of possible completions, where it loops back to what the user initially entered. Backtab (shift+tab) can be used to go backwards through the list.
The list of possible logins is extracted from the garden DB, only when the user actually requests completion.
> Add autocompletion for logins in the visit prompt

- menu_screen.py
Piping invalid data (anything that doesn't exit properly) to botany caused an infinite loop, since `getch` immediately returns `-1` when the input is closed. This PR fixes the issue by raising an `IOError` exception when `getch` returns `-1`, which is then caught in the main loop and exits the program.
> Prevent infinite loops when piping to botany

- menu_screen.py
* Long usernames cause the garden menu to shift over.
* Change `menu_screen.py` to truncate long usernames to a max length of `75`.
I don't work with Python or Curses much. If I'm violating a style guide or something please let me know.
> Limit length of longer usernames

- botany.py
This is a change I had to make to run botany on ~institute. The change is minor and allows botany to run regardless of where python2 is installed on a system, by relying on /usr/bin/env rather than the python2 path.
> changed shebang to increase portability @ahriman/tilde.town

- botany-view.py
python botany-view.py will give you a snapshot look of your garden plot,
showing what is in there. Instead of an interactive curses interface, it
just shows you your plant as it currently is. It's like just taking a
peek through the window, or a picture of your plant to show to your
friends.
I created this because I found it useful myself, wanting to have a way to cron a 'picture' of my plot of land, and show it to the world, at https://tilde.pt/~marado/garden.html .
> botany-view: a new binary giving you a snapshot

- menu_screen.py
The help menu points out to the readme for more info, but, in cases
where people are using this because it is installed on their server, but
they weren't the ones getting it from the web, they probably don't know
where to find that README. It might not happen to many people, but it
happened to me :-)
This patch just adds another line, with the URL for the README.
> Added info about where the readme actually is

- botany.py
Almost all plants seem to get godly rarity (see https://tilde.town/~lucidiot/botany.html and https://tilde.town/~troido/hortus.txt).
python2 division of integers always results in an integer, so `(2/3)` would result in `0`.
This caused all plants to get "godly" as rarity.
This change makes sure a float division is being used.
I don't have an explanation for why there are plants that are not godly (except if they were planted in an older version of botany)
> Stop making all plants godly

- menu_screen.py
The is operator checks if the objects are the same (that is, if id(x) == id(y)). While this might work for small numbers and, I guess, small strings, it could fail just as well. AFAIK, the only literals it should be used with are None, True and False.
This fixes a SyntaxWarning in Python 3.8.6 too.
> don't use "is" to compare string literals

- botany.py
As described in #33 it is possible to kill someone else's plant even if they watered it every day by adding a very old timestamp in visitors.json.
This fixes #33 by ignoring all timestamps that are older than the last time the user themself watered their plant.
It is still possible to crash someone elses viewer by making the structure of their visitors.json incorrect, but at least that will be noticable and reversible.
> Don't let evil visitors kill a plant by adding old timestamps

- botany.py
- menu_screen.py
When user selects harvest action, the confirmation message says:
```
If you harvest your plant you'll start over from a seed.
Continue? (Y/n)
````
The fact that the option 'Y' is in caps, suggests that it is the default option. So, when user only presses enter, it should be the same as pressing Y.
> On harvest confirmation message, default to Y when user presses enter

- plant.py
Python 3.12 no longer supports using non-integer values as arguments for certain random functions (see [Changes in the Python API for 3.12][0]). This PR casts `CONST_RARITY_MAX` to an integer to prevent a `TypeError` from being raised.
[0]: https://docs.python.org/3/whatsnew/3.12.html#changes-in-the-python-api
> Support Python 3.12

- menu_screen.py
At generation 8, the growth rate in the "look" message is displayed as:
> 2.4000000000000004x
To make it display "2.4x" instead, I used the [format specification][0] to display growth rate with only a single decimal place.
[0]: https://docs.python.org/3/library/string.html#format-specification-mini-language
> Round growth rate to single decimal

- botany.py
If the save file is empty, then it will not be loadable, and it is best act as if none existed.
> Check if the save file isn't corrupted

- menu_screen.py
Applies the fix from #54 to the final stage message.
Before:
```
Your next plant will grow at a speed of: 2.4000000000000004x
```
After:
```
Your next plant will grow at a speed of: 2.4x
```
> Round growth rate to single decimal (again)

- botany-view.py
`python botany-view.py` was failing to launch because it tried to use the `datetime` module without importing it. This minimally fixes that.
I like the idea of `botany-view.py`, and it seems like there's ways that we could give it more love beyond this fix. For example, you could imagine able to invoke it with a command like `botany --non-interactive` instead of as a separate script, for discoverability. And there's a comment here pointing out some duplication around the `plant_art_list` variable; we could resolve that. Are you open to more contributions in this direction?
> Fix missing datetime import
